### ISSUE TITLE
icon-square.png is not opening!

### ISSUE THREAD

**Issue by ibhanu** [hackclub/v3#15]
When I tried downloading the icon-square.png it shows an error saying access denied!
Link to the png: https://assets.hackclub.com/icon-square.png
This is the error: This XML file does not appear to have any style information associated with it. The document tree is shown below.
`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>6CAD7BB19A1EDCB6</RequestId>
<HostId>
yHUiu3N5+hS8LNmrHKB7j+yfTnppNE4wFva934BOf2WnFteKtRcXRZ+qqwUWkjheLKyrADKA1mI=
</HostId>
</Error>`

**Comment by lachlanjc** [comment]
Just fixed, sorry about that! Let me know if you spot anything else up.
