### ISSUE TITLE
Update Slack Channels on Website

### ISSUE THREAD

**Issue by lnabegu** [hackclub/v3#176]
It would be nice to update the Slack channels portion of the website so that it's more up-to-date and gives smaller channels more exposure!

**Comment by Manishgupta200** [comment]
I would like to work on it. please, assign it to me.
can you please labeled me as a hacktoberfest-accepted after successfully pull request from me

**Comment by sampoder** [comment]
You've got it! Assigned to you it is.

**Comment by Manishgupta200** [comment]
Yes, please assign it to me
