### ISSUE TITLE
APIs aren't working

### ISSUE THREAD

**Issue by abby9664** [hackclub/v3#56]
Hello!
It looks like hackclub.com/api/channels/dogs and hackclub.com/api/channels/counttoamillion are 404ing right now. Might have had to do with the recent transition of a bunch of pages from v2 to v3. I don't know much about server-side stuff, but I think v3 isn't recognizing the paths, so it's forwarding them to v2.

**Comment by lachlanjc** [comment]
This is fixed! Lmk if you spot any other issues.
